---
- name: Install Git
  apt: pkg=git state=latest

- name: Clone Drupal
  git: >
    repo=http://git.drupal.org/project/drupal.git
    dest=/vagrant/ubercart/
    update=no

- name: Create settings.php
  command: cp /vagrant/ubercart/sites/default/default.settings.php /vagrant/ubercart/sites/default/settings.php

- name: Create services.yml
  command: cp /vagrant/ubercart/sites/default/default.services.yml /vagrant/ubercart/sites/default/services.yml

- name: Update permissions of settings.php
  file: path=/vagrant/ubercart/sites/default/settings.php mode=777

- name: Update permissions of services.yml
  file: path=/vagrant/ubercart/sites/default/services.yml mode=777

- name: Update permissions of files directory
  file: >
    path=/vagrant/ubercart/sites/default/files
    mode=777
    state=directory
    recurse=yes